[package]
name = "oggmeta"
version = "1.0.1"
edition = "2021"
description = "A crate for reading and writing ogg metadata"
license = "MIT"
repository = "https://github.com/hungl6844/oggmeta"
readme = "README.md"

[dependencies]
ogg = "0.9.1"
thiserror = "2.0.0"
theorafile-rs = "0.1.2"
image = { version = "0.25.6", default-features = false, features = ["jpeg"] }
base64 = "0.22.1"
